

# Swagger bug, disable error for java.lang.NumberFormatException: For input string: ""
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error