spring:
  application:
    name: portfolio
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:5432/postgres"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
#    database: "postgresql"
#    properties:
#      hibernate.temp.use_jdbc_metadata_defaults: false
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect