apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 1
  template:
    metadata:
      name: portfolio
      labels:
        app: portfolio
        env: production
    spec:
      containers:
        - name: portfolio
          env:
            - name: SYSTEM_AUTHENTICATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: apitoken
                  key: token
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host
          image: synend/portfolio:1.0.0