kind: Service
apiVersion: v1
metadata:
  name: portfolio
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    role: portfolio
    app: portfolio-app