kind: Service
apiVersion: v1
metadata:
  name: portfolio
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    role: portfolio
    app: portfolio-app